[package]
name = "number_guessing_anti_cheat"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.31.4" # Just specify the version, no need for features
winapi = { version = "0.3", features = ["winbase", "memoryapi", "processthreadsapi", "winnt"] }
